spring.application.name=subscription-tracker
server.port=8080


spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/subscription_tracker}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:scrie_parola_ta_de_db_aici_doar_cand_testezi_local}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER:g@gmail.com}
spring.mail.password=${MAIL_PASSWORD:scrie_parola_de_la_google_aici_doar_cand_testezi_local}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
jwt.secret=${JWT_SECRET:subscription_tracker_secret_key_very_long_and_secure_2024}
jwt.expiration=86400000